export const predefinedCategories = [
  // Incoming categories
  "atm/bank deposit",
  "benefits",
  "cashback",
  "chargeback",
  "ecommerce",
  "freelance",
  "gambling",
  "grants or stipends",
  "insurance",
  "inter account transfer",
  "interest / dividend",
  "intra account transfer",
  "loans",
  "not enough information",
  "other",
  "pawn loan",
  "paycheck",
  "peer to peer transfer",
  "pension",
  "property rental",
  "refund",
  "reversal / adjustment",
  "rideshare or delivery income",
  "tax refund",
  "trading (crypto)",
  "trading (non-crypto)",
  
  // Outgoing categories
  "app stores",
  "atm/bank withdrawal",
  "auto lease payment",
  "auto loan repayment",
  "bank fee",
  "books, newsletters, newspapers",
  "buy now, pay later",
  "cafes and coffee shops",
  "childcare",
  "clothing",
  "contribution to reserve fund",
  "convenience store",
  "council tax",
  "credit card bill",
  "credit card fee",
  "credit report",
  "debt collection",
  "department or discount store",
  "digital content / streaming",
  "donation",
  "drugstores and pharmacies",
  "eCommerce purchase",
  "education",
  "electronics",
  "entertainment and recreation",
  "firearms",
  "food and drink",
  "fuel",
  "funerals and bequests",
  "gambling",
  "gifts",
  "government",
  "groceries",
  "home improvements and maintenance services",
  "hotel or lodging",
  "insurance",
  "inter account transfer",
  "interest",
  "intra account transfer",
  "investment",
  "laundry",
  "legal services",
  "liquor",
  "loan repayment",
  "media",
  "medical bill",
  "mortgage",
  "non-sufficient funds / overdraft fee",
  "not enough information",
  "other consumer services",
  "other non-essential",
  "other transport",
  "pawn shops",
  "peer to peer transfer",
  "pets",
  "public transport",
  "recreational goods",
  "rent and property management fee",
  "rent to own",
  "retirement contributions",
  "ridesharing and taxis",
  "saas tools",
  "self care",
  "sport and fitness",
  "student loan repayment",
  "taxes",
  "toll charge",
  "towing companies",
  "trading (crypto)",
  "trading (non-crypto)",
  "utilities",
  "vehicle maintenance",
] as const;

export type Category = typeof predefinedCategories[number]; 