export * from './application.service';
import { ApplicationService } from './application.service';
export * from './application.serviceInterface';
export * from './applicationManagement.service';
import { ApplicationManagementService } from './applicationManagement.service';
export * from './applicationManagement.serviceInterface';
export * from './authorisations.service';
import { AuthorisationsService } from './authorisations.service';
export * from './authorisations.serviceInterface';
export * from './consents.service';
import { ConsentsService } from './consents.service';
export * from './consents.serviceInterface';
export * from './constraints.service';
import { ConstraintsService } from './constraints.service';
export * from './constraints.serviceInterface';
export * from './enrichment.service';
import { EnrichmentService } from './enrichment.service';
export * from './enrichment.serviceInterface';
export * from './financialData.service';
import { FinancialDataService } from './financialData.service';
export * from './financialData.serviceInterface';
export * from './hostedConsentPages.service';
import { HostedConsentPagesService } from './hostedConsentPages.service';
export * from './hostedConsentPages.serviceInterface';
export * from './hostedPaymentPages.service';
import { HostedPaymentPagesService } from './hostedPaymentPages.service';
export * from './hostedPaymentPages.serviceInterface';
export * from './institutions.service';
import { InstitutionsService } from './institutions.service';
export * from './institutions.serviceInterface';
export * from './notifications.service';
import { NotificationsService } from './notifications.service';
export * from './notifications.serviceInterface';
export * from './payments.service';
import { PaymentsService } from './payments.service';
export * from './payments.serviceInterface';
export * from './users.service';
import { UsersService } from './users.service';
export * from './users.serviceInterface';
export * from './variableRecurringPayments.service';
import { VariableRecurringPaymentsService } from './variableRecurringPayments.service';
export * from './variableRecurringPayments.serviceInterface';
export * from './webhooks.service';
import { WebhooksService } from './webhooks.service';
export * from './webhooks.serviceInterface';
export const APIS = [ApplicationService, ApplicationManagementService, AuthorisationsService, ConsentsService, ConstraintsService, EnrichmentService, FinancialDataService, HostedConsentPagesService, HostedPaymentPagesService, InstitutionsService, NotificationsService, PaymentsService, UsersService, VariableRecurringPaymentsService, WebhooksService];
