/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiResponseError } from '../model/models';
import { Application } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ApplicationServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get Application Self
     * Get the information about the institutions configured in your application
     */
    getApplicationMe(extraHttpRequestParams?: any): Observable<Application>;

}
