/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiListResponseOfDataConstraints } from '../model/models';
import { ApiListResponseOfPaymentConstraints } from '../model/models';
import { ApiResponseError } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ConstraintsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get Data Constraints Rules
     * Get Data Constraints Rules against an Institution for Account Authorisation requests
     * @param institutionIds Unique Id(s) of the &#x60;Institution&#x60;(s) to retrieve the Data Constraints for. Multiple institutionIds need to be separated by &#x60;,&#x60;
     * @param institutionCountryCode Country code of the &#x60;Institution&#x60;(s). Ensure that the country code matches the respective institutionIds; any mismatch will result in an HTTP 404 error response.
     * @param endpointPath The path on the API that is associated with the operation for which constraints are to be retrieved
     * @param endpointMethod The HTTP method that is associated with the operation for which constraints are to be retrieved
     */
    getAccountConstraintsRulesByInstitution(institutionIds: Array<string>, institutionCountryCode: string, endpointPath?: string, endpointMethod?: 'POST' | 'PATCH' | 'PUT' | 'GET' | 'DELETE', extraHttpRequestParams?: any): Observable<ApiListResponseOfDataConstraints>;

    /**
     * Get Payment Constraints Rules
     * Retrieve institution specific constraints for payment authorisation and submission requests
     * @param institutionIds Unique Id(s) of the &#x60;Institution&#x60;(s) to retrieve the Payment Constraints for. Multiple institutionIds need to be separated by &#x60;,&#x60;
     * @param institutionCountryCode Country code of the &#x60;Institution&#x60;(s). Ensure that the country code matches the respective institutionIds; any mismatch will result in an HTTP 404 error response.
     * @param paymentType Type of payment to retrieve payment constraints for
     * @param endpointPath The path on the API that is associated with the operation for which constraints are to be retrieved
     * @param endpointMethod The HTTP method that is associated with the operation for which constraints are to be retrieved
     */
    getPaymentConstraintsRulesByInstitution(institutionIds: Array<string>, institutionCountryCode: string, paymentType: 'DOMESTIC_PAYMENT' | 'DOMESTIC_INSTANT_PAYMENT' | 'DOMESTIC_VARIABLE_RECURRING_PAYMENT' | 'DOMESTIC_SCHEDULED_PAYMENT' | 'DOMESTIC_PERIODIC_PAYMENT' | 'INTERNATIONAL_PAYMENT' | 'INTERNATIONAL_SCHEDULED_PAYMENT' | 'INTERNATIONAL_PERIODIC_PAYMENT', endpointPath?: string, endpointMethod?: 'POST' | 'PATCH' | 'PUT' | 'GET' | 'DELETE', extraHttpRequestParams?: any): Observable<ApiListResponseOfPaymentConstraints>;

}
