/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiResponseError } from '../model/models';
import { ApiResponseOfCreateHostedConsentRequest } from '../model/models';
import { ApiResponseOfGetHostedConsentRequest } from '../model/models';
import { CreateHostedConsentRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface HostedConsentPagesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create Hosted Consent Request
     * Used to initiate a consent request using Yapily Hosted Pages.
     * @param createHostedConsentRequest 
     */
    createHostedConsentRequest(createHostedConsentRequest: CreateHostedConsentRequest, extraHttpRequestParams?: any): Observable<ApiResponseOfCreateHostedConsentRequest>;

    /**
     * Get Hosted Consent Request
     * Used to get details of a hosted consent request
     * @param consentRequestId Unique Identifier of the consent request
     */
    getHostedConsentRequest(consentRequestId: string, extraHttpRequestParams?: any): Observable<ApiResponseOfGetHostedConsentRequest>;

}
