/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiListResponseOfFeatureDetails } from '../model/models';
import { ApiListResponseOfInstitution } from '../model/models';
import { ApiResponseError } from '../model/models';
import { Institution } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface InstitutionsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get Features
     * Used to retrieve all features available from Yapily. Each &#x60;Institution&#x60; supports a one, many or all of these features and can be seen in the features field of the &#x60;Institution&#x60; object.&lt;br&gt;&lt;br&gt;Note: Every &#x60;Institution&#x60; does not necessarily support every feature. To see which features are available for a particular Institution, use either the [Get Institutions](https://docs.yapily.com/api/reference/#operation/getInstitutions) or [Get Institution](https://docs.yapily.com/api/reference/#operation/getInstitution) endpoint and check the features array within the &#x60;Institution&#x60; payload.
     */
    getFeatureDetails(extraHttpRequestParams?: any): Observable<ApiListResponseOfFeatureDetails>;

    /**
     * Get Institution
     * Used to retrieves details of a specific &#x60;Institution&#x60; within an application
     * @param institutionId __Mandatory__. The Yapily institution Id for the &#x60;Institution&#x60;.
     */
    getInstitution(institutionId: string, extraHttpRequestParams?: any): Observable<Institution>;

    /**
     * Get Institutions
     * Used to retrieve all &#x60;Institutions&#x60; within an application
     */
    getInstitutions(extraHttpRequestParams?: any): Observable<ApiListResponseOfInstitution>;

}
