/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiResponseError } from '../model/models';
import { ApiResponseOfUserDeleteResponse } from '../model/models';
import { ApplicationUser } from '../model/models';
import { NewApplicationUser } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface UsersServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Create User
     * Create a new user in your application
     * @param newApplicationUser 
     */
    addUser(newApplicationUser: NewApplicationUser, extraHttpRequestParams?: any): Observable<ApplicationUser>;

    /**
     * Delete User
     * Delete a user from your application along with any sub-resources (including consent resources on institution APIs if they exist)
     * @param userUuid __Mandatory__. The Yapily generated UUID for the user.
     */
    deleteUser(userUuid: string, extraHttpRequestParams?: any): Observable<ApiResponseOfUserDeleteResponse>;

    /**
     * Get User
     * Get a specific user using the user UUID
     * @param userUuid __Mandatory__. The Yapily generated UUID for the user.
     */
    getUser(userUuid: string, extraHttpRequestParams?: any): Observable<ApplicationUser>;

    /**
     * Get Users
     * Get all the users configured in your application
     * @param filterApplicationUserId __Optional__. Filter records based on the list of &#x60;applicationUserId&#x60; users provided.
     */
    getUsers(filterApplicationUserId?: Set<string>, extraHttpRequestParams?: any): Observable<Array<ApplicationUser>>;

}
