/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountRequest } from './accountRequest';
import { RedirectRequest } from './redirectRequest';


export interface AccountAuthorisationRequest { 
    /**
     * `User` for which the authorisation request was created.
     */
    userUuid?: string;
    /**
     * __Conditional__. User-friendly identifier of the `User` that provides authorisation. If a `User` with the specified `applicationUserId` exists, it will be used otherwise, a new `User` with the specified `applicationUserId` will be created and used. Either the `userUuid` or `applicationUserId` must be provided.
     */
    applicationUserId?: string;
    /**
     * Extra parameters the TPP may want to get forwarded in the callback request after the PSU redirect.
     */
    forwardParameters?: Array<string>;
    /**
     * __Mandatory__. The reference to the `Institution` which identifies which institution the authorisation request is sent to.
     */
    institutionId: string;
    /**
     * __Optional__. The server to redirect the user to after the user completes the authorisation at the `Institution`. <br><br>See [Using a callback (Optional)](https://docs.yapily.com/pages/knowledge/yapily-concepts/callback_url/#using-a-callback-optional) for more information.
     */
    callback?: string;
    redirect?: RedirectRequest;
    /**
     * __Conditional__. Used to receive a `oneTimeToken` rather than a `consentToken` at the `callback` for additional security. This can only be used when the `callback` is set. <br><br>See [Using a callback with an OTT (Optional)](https://docs.yapily.com/pages/knowledge/yapily-concepts/callback_url/#using-a-callback-with-an-ott-optional) for more information.
     */
    oneTimeToken?: boolean;
    accountRequest?: AccountRequest;
}

