/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The type of account e.g. (Credit Card, Savings).
 */
export type AccountType = 'CASH_TRADING' | 'CASH_INCOME' | 'CASH_PAYMENT' | 'CHARGE_CARD' | 'CHARGES' | 'COMMISSION' | 'CREDIT_CARD' | 'CURRENT' | 'E_MONEY' | 'LIMITED_LIQUIDITY_SAVINGS_ACCOUNT' | 'LOAN' | 'MARGINAL_LENDING' | 'MONEY_MARKET' | 'MORTGAGE' | 'NON_RESIDENT_EXTERNAL' | 'OTHER' | 'OVERDRAFT' | 'OVERNIGHT_DEPOSIT' | 'PREPAID_CARD' | 'SALARY' | 'SAVINGS' | 'SETTLEMENT' | 'TAX' | 'UNKNOWN';

export const AccountType = {
    CashTrading: 'CASH_TRADING' as AccountType,
    CashIncome: 'CASH_INCOME' as AccountType,
    CashPayment: 'CASH_PAYMENT' as AccountType,
    ChargeCard: 'CHARGE_CARD' as AccountType,
    Charges: 'CHARGES' as AccountType,
    Commission: 'COMMISSION' as AccountType,
    CreditCard: 'CREDIT_CARD' as AccountType,
    Current: 'CURRENT' as AccountType,
    EMoney: 'E_MONEY' as AccountType,
    LimitedLiquiditySavingsAccount: 'LIMITED_LIQUIDITY_SAVINGS_ACCOUNT' as AccountType,
    Loan: 'LOAN' as AccountType,
    MarginalLending: 'MARGINAL_LENDING' as AccountType,
    MoneyMarket: 'MONEY_MARKET' as AccountType,
    Mortgage: 'MORTGAGE' as AccountType,
    NonResidentExternal: 'NON_RESIDENT_EXTERNAL' as AccountType,
    Other: 'OTHER' as AccountType,
    Overdraft: 'OVERDRAFT' as AccountType,
    OvernightDeposit: 'OVERNIGHT_DEPOSIT' as AccountType,
    PrepaidCard: 'PREPAID_CARD' as AccountType,
    Salary: 'SALARY' as AccountType,
    Savings: 'SAVINGS' as AccountType,
    Settlement: 'SETTLEMENT' as AccountType,
    Tax: 'TAX' as AccountType,
    Unknown: 'UNKNOWN' as AccountType
};

