/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Specifies the type of the stated account balance.
 */
export type AccountBalanceType = 'CLOSING_AVAILABLE' | 'CLOSING_BOOKED' | 'CLOSING_CLEARED' | 'EXPECTED' | 'FORWARD_AVAILABLE' | 'INFORMATION' | 'INTERIM_AVAILABLE' | 'INTERIM_BOOKED' | 'INTERIM_CLEARED' | 'OPENING_AVAILABLE' | 'OPENING_BOOKED' | 'OPENING_CLEARED' | 'PREVIOUSLY_CLOSED_BOOKED' | 'AUTHORISED' | 'OTHER' | 'UNKNOWN';

export const AccountBalanceType = {
    ClosingAvailable: 'CLOSING_AVAILABLE' as AccountBalanceType,
    ClosingBooked: 'CLOSING_BOOKED' as AccountBalanceType,
    ClosingCleared: 'CLOSING_CLEARED' as AccountBalanceType,
    Expected: 'EXPECTED' as AccountBalanceType,
    ForwardAvailable: 'FORWARD_AVAILABLE' as AccountBalanceType,
    Information: 'INFORMATION' as AccountBalanceType,
    InterimAvailable: 'INTERIM_AVAILABLE' as AccountBalanceType,
    InterimBooked: 'INTERIM_BOOKED' as AccountBalanceType,
    InterimCleared: 'INTERIM_CLEARED' as AccountBalanceType,
    OpeningAvailable: 'OPENING_AVAILABLE' as AccountBalanceType,
    OpeningBooked: 'OPENING_BOOKED' as AccountBalanceType,
    OpeningCleared: 'OPENING_CLEARED' as AccountBalanceType,
    PreviouslyClosedBooked: 'PREVIOUSLY_CLOSED_BOOKED' as AccountBalanceType,
    Authorised: 'AUTHORISED' as AccountBalanceType,
    Other: 'OTHER' as AccountBalanceType,
    Unknown: 'UNKNOWN' as AccountBalanceType
};

