/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Statement information belonging to the account.
 */
export interface AccountStatement { 
    /**
     * Unique identifier for the statement.
     */
    id?: string;
    /**
     * Date and time of when the statement period starts.
     */
    startDateTime?: string;
    /**
     * Date and time of when the statement period ends.
     */
    endDateTime?: string;
    /**
     * Date and time of when the statement was created.
     */
    creationDateTime?: string;
}

