/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Used to describe the format of the account.<br><br> See [Account Identification Combinations](https://docs.yapily.com/pages/key-concepts/payments/payment-execution/intro-to-payment-execution/#account-identifications-combinations) for more information.
 */
export type AccountIdentificationTypeResponse = 'SORT_CODE' | 'ACCOUNT_NUMBER' | 'IBAN' | 'BBAN' | 'BIC' | 'PAN' | 'MASKED_PAN' | 'MSISDN' | 'BSB' | 'NCC' | 'ABA' | 'ABA_WIRE' | 'ABA_ACH' | 'EMAIL' | 'ROLL_NUMBER' | 'BLZ' | 'IFS' | 'CLABE' | 'CTN' | 'BRANCH_CODE' | 'VIRTUAL_ACCOUNT_ID';

export const AccountIdentificationTypeResponse = {
    SortCode: 'SORT_CODE' as AccountIdentificationTypeResponse,
    AccountNumber: 'ACCOUNT_NUMBER' as AccountIdentificationTypeResponse,
    Iban: 'IBAN' as AccountIdentificationTypeResponse,
    Bban: 'BBAN' as AccountIdentificationTypeResponse,
    Bic: 'BIC' as AccountIdentificationTypeResponse,
    Pan: 'PAN' as AccountIdentificationTypeResponse,
    MaskedPan: 'MASKED_PAN' as AccountIdentificationTypeResponse,
    Msisdn: 'MSISDN' as AccountIdentificationTypeResponse,
    Bsb: 'BSB' as AccountIdentificationTypeResponse,
    Ncc: 'NCC' as AccountIdentificationTypeResponse,
    Aba: 'ABA' as AccountIdentificationTypeResponse,
    AbaWire: 'ABA_WIRE' as AccountIdentificationTypeResponse,
    AbaAch: 'ABA_ACH' as AccountIdentificationTypeResponse,
    Email: 'EMAIL' as AccountIdentificationTypeResponse,
    RollNumber: 'ROLL_NUMBER' as AccountIdentificationTypeResponse,
    Blz: 'BLZ' as AccountIdentificationTypeResponse,
    Ifs: 'IFS' as AccountIdentificationTypeResponse,
    Clabe: 'CLABE' as AccountIdentificationTypeResponse,
    Ctn: 'CTN' as AccountIdentificationTypeResponse,
    BranchCode: 'BRANCH_CODE' as AccountIdentificationTypeResponse,
    VirtualAccountId: 'VIRTUAL_ACCOUNT_ID' as AccountIdentificationTypeResponse
};

