/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountBalance } from './accountBalance';
import { ConsolidatedAccountInformation } from './consolidatedAccountInformation';
import { AccountIdentification } from './accountIdentification';
import { AccountType } from './accountType';
import { UsageType } from './usageType';
import { AccountName } from './accountName';


export interface Account { 
    /**
     * Unique identifier of the account.
     */
    id?: string;
    /**
     * Specifies the type of account e.g. (BUSINESS_CURRENT).
     */
    type?: string;
    /**
     * Product name as defined by the financial institution for this account
     */
    description?: string;
    /**
     * Main / headline balance for the account. <br><br> Use of this field is recommended as fallback only. Instead, use of the typed balances (accountBalances) is recommended.
     */
    balance?: number;
    /**
     * Currency the bank account balance is denoted in. <br><br> Specified as a 3-letter ISO 4217 currency code
     */
    currency?: string;
    usageType?: UsageType;
    accountType?: AccountType;
    /**
     * Nickname of the account that was provided by the account owner. <br><br> May be used to aid identification of the account.
     */
    nickname?: string;
    /**
     * Supplementary specifications that might be provided by the Bank. These provide further characteristics about the account.
     */
    details?: string;
    accountNames?: Array<AccountName>;
    accountIdentifications?: Set<AccountIdentification>;
    accountBalances?: Array<AccountBalance>;
    consolidatedAccountInformation?: ConsolidatedAccountInformation;
}
export namespace Account {
}


