/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Account } from './account';
import { ResponseForwardedData } from './responseForwardedData';
import { ResponseListMeta } from './responseListMeta';
import { FilteredClientPayloadListAccount } from './filteredClientPayloadListAccount';
import { RawResponse } from './rawResponse';


export interface AccountApiListResponse { 
    meta?: ResponseListMeta;
    data?: Array<Account>;
    links?: { [key: string]: string; };
    forwardedData?: Array<ResponseForwardedData>;
    /** @deprecated */
    raw?: Array<RawResponse>;
    paging?: FilteredClientPayloadListAccount;
    tracingId?: string;
}

