/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressTypeEnum } from './addressTypeEnum';


/**
 * __Conditional__. The address of the `Payee` or `Payer`.<ul><li>`payee.address` is mandatory when the `paymentType` is an `INTERNATIONAL` payment</li><li>An `Institution` may require you to specify the `country` when used in the context of the `Payee` to be able to make a payment.</li></ul>
 */
export interface Address { 
    /**
     * __Optional__. The address line of the address
     */
    addressLines?: Array<string>;
    /**
     * __Optional__. The street name of the address
     */
    streetName?: string;
    /**
     * __Optional__. The building number of the address
     */
    buildingNumber?: string;
    /**
     * __Optional__. The post code of the address
     */
    postCode?: string;
    /**
     * __Optional__. The town name of the address
     */
    townName?: string;
    /**
     * __Optional__. The list of counties for the address
     */
    county?: Array<string>;
    /**
     * __Conditional__. The 2-letter country code for the address. <br><br>An `Institution` may require you to specify the `country` when used in the context of the `Payee` to be able to make a payment
     */
    country?: string;
    /**
     * __Optional__. The department for the address
     */
    department?: string;
    /**
     * __Optional__. The sub-department for the address
     */
    subDepartment?: string;
    addressType?: AddressTypeEnum;
}
export namespace Address {
}


