/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * __Mandatory__. Period alignment for which the payment limits are enforced. Allowed values are [CONSENT, CALENDAR]. If CONSENT, then period starts on consent creation date. If CALENDAR, then period lines up with the frequency e.g. WEEKLY period will begin at start of the week in question.
 */
export type AlignmentEnum = 'CONSENT' | 'CALENDAR';

export const AlignmentEnum = {
    Consent: 'CONSENT' as AlignmentEnum,
    Calendar: 'CALENDAR' as AlignmentEnum
};

