/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApiErrorResponseV2Error } from './apiErrorResponseV2Error';


/**
 * API Error Response
 */
export interface ApiErrorResponseV2 { 
    error?: ApiErrorResponseV2Error;
}

