/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApiListResponseOfRealTimeTransactionLinks { 
    /**
     * A cursor or link to the first page in the data set.
     */
    first?: string;
    /**
     * A cursor or link to the previous page in the data set.
     */
    prev?: string;
    /**
     * A cursor or link to the current page in the data set.
     */
    self?: string;
    /**
     * A cursor or link to the next page in the data set.
     */
    next?: string;
    /**
     * A cursor or link to the last page in the data set.
     */
    last?: string;
}

