/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FilteredClientPayloadListInstitution } from './filteredClientPayloadListInstitution';
import { ResponseForwardedData } from './responseForwardedData';
import { ResponseListMeta } from './responseListMeta';
import { Institution } from './institution';
import { RawResponse } from './rawResponse';


export interface ApiListResponseOfInstitution { 
    meta?: ResponseListMeta;
    data?: Array<Institution>;
    links?: { [key: string]: string; };
    forwardedData?: Array<ResponseForwardedData>;
    /** @deprecated */
    raw?: Array<RawResponse>;
    paging?: FilteredClientPayloadListInstitution;
    tracingId?: string;
}

