/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FilteredClientPayloadListAccountStatement } from './filteredClientPayloadListAccountStatement';
import { ResponseForwardedData } from './responseForwardedData';
import { ResponseListMeta } from './responseListMeta';
import { AccountStatement } from './accountStatement';
import { RawResponse } from './rawResponse';


export interface ApiListResponseOfAccountStatement { 
    meta?: ResponseListMeta;
    data?: Array<AccountStatement>;
    links?: { [key: string]: string; };
    forwardedData?: Array<ResponseForwardedData>;
    /** @deprecated */
    raw?: Array<RawResponse>;
    paging?: FilteredClientPayloadListAccountStatement;
    tracingId?: string;
}

