/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DirectDebitResponse } from './directDebitResponse';
import { ResponseForwardedData } from './responseForwardedData';
import { ResponseListMeta } from './responseListMeta';
import { FilteredClientPayloadListDirectDebitResponse } from './filteredClientPayloadListDirectDebitResponse';
import { RawResponse } from './rawResponse';


export interface ApiListResponseOfDirectDebitResponse { 
    meta?: ResponseListMeta;
    data?: Array<DirectDebitResponse>;
    links?: { [key: string]: string; };
    forwardedData?: Array<ResponseForwardedData>;
    /** @deprecated */
    raw?: Array<RawResponse>;
    paging?: FilteredClientPayloadListDirectDebitResponse;
    tracingId?: string;
}

