/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EventSubscriptionResponse } from './eventSubscriptionResponse';
import { FilteredClientPayloadListTransaction } from './filteredClientPayloadListTransaction';
import { ResponseForwardedData } from './responseForwardedData';
import { ResponseListMeta } from './responseListMeta';
import { RawResponse } from './rawResponse';


export interface ApiListResponseOfEventSubscriptionResponse { 
    meta?: ResponseListMeta;
    data?: Array<EventSubscriptionResponse>;
    links?: { [key: string]: string; };
    forwardedData?: Array<ResponseForwardedData>;
    /** @deprecated */
    raw?: Array<RawResponse>;
    paging?: FilteredClientPayloadListTransaction;
    tracingId?: string;
}

