/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResponseForwardedData } from './responseForwardedData';
import { ResponseListMeta } from './responseListMeta';
import { Beneficiary } from './beneficiary';
import { RawResponse } from './rawResponse';


export interface ApiListResponseOfBeneficiary { 
    meta?: ResponseListMeta;
    data?: Array<Beneficiary>;
    links?: { [key: string]: string; };
    forwardedData?: Array<ResponseForwardedData>;
    /** @deprecated */
    raw?: Array<RawResponse>;
    tracingId?: string;
}

