/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApplicationResponseListMeta } from './applicationResponseListMeta';
import { ApplicationResponse } from './applicationResponse';


export interface ApiListOfApplicationResponse { 
    meta?: ApplicationResponseListMeta;
    data?: Array<ApplicationResponse>;
}

