/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FilteredClientPayloadListTransaction } from './filteredClientPayloadListTransaction';
import { ResponseForwardedData } from './responseForwardedData';
import { Transaction } from './transaction';
import { ResponseListMeta } from './responseListMeta';
import { RawResponse } from './rawResponse';


export interface ApiListResponseOfTransaction { 
    meta?: ResponseListMeta;
    data?: Array<Transaction>;
    links?: { [key: string]: string; };
    forwardedData?: Array<ResponseForwardedData>;
    /** @deprecated */
    raw?: Array<RawResponse>;
    paging?: FilteredClientPayloadListTransaction;
    tracingId?: string;
}

