/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResponseForwardedData } from './responseForwardedData';
import { ResponseMeta } from './responseMeta';
import { AccountAuthorisationResponse } from './accountAuthorisationResponse';
import { RawResponse } from './rawResponse';


export interface ApiResponseOfAccountAuthorisationResponse { 
    meta?: ResponseMeta;
    data?: AccountAuthorisationResponse;
    links?: { [key: string]: string; };
    forwardedData?: Array<ResponseForwardedData>;
    /** @deprecated */
    raw?: Array<RawResponse>;
    tracingId?: string;
}

