/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResponseMeta } from './responseMeta';
import { HostedPaymentRequestResponse } from './hostedPaymentRequestResponse';


export interface ApiResponseOfCreateHostedPaymentRequestLink { 
    meta?: ResponseMeta;
    data?: HostedPaymentRequestResponse;
}

