/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResponseMeta } from './responseMeta';
import { HostedConsentRequestResponse } from './hostedConsentRequestResponse';


export interface ApiResponseOfCreateHostedConsentRequest { 
    meta?: ResponseMeta;
    data?: HostedConsentRequestResponse;
}

