/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HostedGetConsentRequestResponse } from './hostedGetConsentRequestResponse';
import { ResponseMeta } from './responseMeta';


export interface ApiResponseOfGetHostedConsentRequest { 
    meta?: ResponseMeta;
    data?: HostedGetConsentRequestResponse;
}

