/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResponseMeta } from './responseMeta';
import { HostedPaymentDetails } from './hostedPaymentDetails';


export interface ApiResponseOfGetHostedPaymentRequest { 
    meta?: ResponseMeta;
    data?: HostedPaymentDetails;
}

