/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Media } from './media';
import { Institution } from './institution';


/**
 * Information about the application.
 */
export interface Application { 
    /**
     * Unique identification for the `Application` as assigned by Yapily.
     */
    uuid?: string;
    /**
     * The individual name of the `Application`.
     */
    name?: string;
    /**
     * States whether an `Application` is active.
     */
    active?: boolean;
    authCallbacks?: Array<string>;
    institutions?: Set<Institution>;
    media?: Set<Media>;
    /**
     * Date and time of when the application was created.
     */
    created?: string;
    /**
     * Date and time of when the application was last updated.
     */
    updated?: string;
}

