/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ApplicationResponseListMetaPaginationSelf } from './applicationResponseListMetaPaginationSelf';


export interface ApplicationResponseListMetaPagination { 
    self?: ApplicationResponseListMetaPaginationSelf;
    /**
     * The total number of applications that match the given filter.
     */
    totalCount?: number;
}

