/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InstitutionConsent } from './institutionConsent';


/**
 * Information about a user of an application.
 */
export interface ApplicationUser { 
    /**
     * A unique identifier for the \'User\' assigned by Yapily.
     */
    uuid?: string;
    /**
     * Unique identifier of the application the user is associated with.
     */
    applicationUuid?: string;
    /**
     * __Conditional__. The user-friendly reference to the `User`.
     */
    applicationUserId?: string;
    referenceId?: string;
    /**
     * Date and time of when the user was created.
     */
    createdAt?: string;
    institutionConsents?: Array<InstitutionConsent>;
}

