/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ApplicationResponseListMetaPaginationSelf { 
    /**
     * The number of skipped applications.
     */
    offset?: number;
    /**
     * The maximum number of applications for the current page.
     */
    limit?: number;
    /**
     * The field by which results are sorted by. Default direction is ascending, descending is identified by a \"-\" prefix.
     */
    sort?: string;
}

