/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Current status of the embedded authorisation request in code form.
 */
export type AuthorisationStatus = 'AWAITING_AUTHORIZATION' | 'AWAITING_FURTHER_AUTHORIZATION' | 'AWAITING_RE_AUTHORIZATION' | 'AUTHORIZED' | 'CONSUMED' | 'REJECTED' | 'REVOKED' | 'FAILED' | 'EXPIRED' | 'UNKNOWN' | 'INVALID' | 'AWAITING_DECOUPLED_PRE_AUTHORIZATION' | 'AWAITING_PRE_AUTHORIZATION' | 'PRE_AUTHORIZED' | 'AWAITING_DECOUPLED_AUTHORIZATION' | 'AWAITING_SCA_METHOD' | 'AWAITING_SCA_CODE';

export const AuthorisationStatus = {
    AwaitingAuthorization: 'AWAITING_AUTHORIZATION' as AuthorisationStatus,
    AwaitingFurtherAuthorization: 'AWAITING_FURTHER_AUTHORIZATION' as AuthorisationStatus,
    AwaitingReAuthorization: 'AWAITING_RE_AUTHORIZATION' as AuthorisationStatus,
    Authorized: 'AUTHORIZED' as AuthorisationStatus,
    Consumed: 'CONSUMED' as AuthorisationStatus,
    Rejected: 'REJECTED' as AuthorisationStatus,
    Revoked: 'REVOKED' as AuthorisationStatus,
    Failed: 'FAILED' as AuthorisationStatus,
    Expired: 'EXPIRED' as AuthorisationStatus,
    Unknown: 'UNKNOWN' as AuthorisationStatus,
    Invalid: 'INVALID' as AuthorisationStatus,
    AwaitingDecoupledPreAuthorization: 'AWAITING_DECOUPLED_PRE_AUTHORIZATION' as AuthorisationStatus,
    AwaitingPreAuthorization: 'AWAITING_PRE_AUTHORIZATION' as AuthorisationStatus,
    PreAuthorized: 'PRE_AUTHORIZED' as AuthorisationStatus,
    AwaitingDecoupledAuthorization: 'AWAITING_DECOUPLED_AUTHORIZATION' as AuthorisationStatus,
    AwaitingScaMethod: 'AWAITING_SCA_METHOD' as AuthorisationStatus,
    AwaitingScaCode: 'AWAITING_SCA_CODE' as AuthorisationStatus
};

