/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountBalance } from './accountBalance';
import { Amount } from './amount';


export interface Balances { 
    mainBalanceAmount?: Amount;
    balances?: Array<AccountBalance>;
}

