/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BeneficiaryPayee } from './beneficiaryPayee';


/**
 * Account information belonging to the target beneficiary (person/ business).
 */
export interface Beneficiary { 
    /**
     * Unique identifier of the `beneficiary`.
     */
    id?: string;
    /**
     * A creditor reference that is requested to be used for all payment instructions to this beneficiary.
     */
    reference?: string;
    payee?: BeneficiaryPayee;
    /**
     * Indicates whether the account owner has stated that this beneficiary should be trusted. This often results in reduced authentication and authorisation requirements on payments to the beneficiary.
     */
    trusted?: boolean;
}

