/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetBulkPaymentStatus200ResponseMeta } from './getBulkPaymentStatus200ResponseMeta';
import { BulkPaymentDetailsByIdResponseData } from './bulkPaymentDetailsByIdResponseData';


export interface BulkPaymentDetailsByIdResponse { 
    meta?: GetBulkPaymentStatus200ResponseMeta;
    data?: BulkPaymentDetailsByIdResponseData;
}

