/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ComplianceDataPayer } from './complianceDataPayer';


/**
 * __Conditional__. Information needed to complete compliance checks. Mandatory for Yapily Connect customers.
 */
export interface ComplianceData { 
    payer?: ComplianceDataPayer;
}

