/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ComplianceDataAddress } from './complianceDataAddress';


/**
 * __Conditional__. Mandatory if the type is BUSINESS.
 */
export interface ComplianceDataBusiness { 
    /**
     * This is the registered company name of your end user.
     */
    name: string;
    /**
     * This is the registered company number of the business.
     */
    registrationNumber: string;
    registeredAddress: ComplianceDataAddress;
    tradingAddress?: ComplianceDataAddress;
}

