/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An array of `Country` denoting which regions the `Institution` provides coverage for
 */
export interface Country { 
    /**
     * Country name.
     */
    displayName?: string;
    /**
     * Two character ISO 3166 country code.
     */
    countryCode2?: string;
}

