/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HostedPaymentRequestDetailsLink } from './hostedPaymentRequestDetailsLink';
import { UserSettings } from './userSettings';
import { InstitutionIdentifiers } from './institutionIdentifiers';


export interface CreateHostedPaymentRequestLink { 
    /**
     * __Conditional__. Yapily Identifier for the `User` returned by the create user step POST /users. You must either provide `userId` or `applicationUserId`.
     */
    userId?: string;
    /**
     * __Conditional__. Your own `User` reference. If you want to work with their own unique references for individual PSUs then you can use the `applicationUserId` property to provide that value. Where Yapily does not already have a Yapily userId that matches the supplied `applicationUserId`, then a new Yapily userId is created automatically and linked to the `applicationUserId` value. You must either provide userId or `applicationUserId`.
     */
    applicationUserId?: string;
    institutionIdentifiers: InstitutionIdentifiers;
    userSettings?: UserSettings;
    /**
     * URL of your server to redirect the user after completion of the payment flow.
     */
    redirectUrl: string;
    /**
     * The date and time that the authorisation expires. Must be between 10 minutes and 30 days in the future. If not specified, the authorisation URL will expire 10 minutes after creation.
     */
    authorisationExpiresAt?: string;
    paymentRequestDetails: HostedPaymentRequestDetailsLink;
}

