/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserSettings } from './userSettings';
import { VRPSetupRequest } from './vRPSetupRequest';
import { InstitutionIdentifiers } from './institutionIdentifiers';


export interface CreateHostedVRPConsentRequest { 
    /**
     * __Conditional__. Yapily Identifier for the `User` returned by the create user step POST /users. Clients must either provide userId or applicationUserId.
     */
    userId?: string;
    /**
     * __Conditional__. Client\'s own `User` reference. If the client wants to work with their own unique references for individual PSUs then they can use the applicationUserId property to provide that value. Where Yapily does not already have a Yapily userId that matches the supplied applicationUserId, then a new Yapily userId is created automatically and linked to the applicationUserId value. Clients must either provide userId or applicationUserId.
     */
    applicationUserId?: string;
    institutionIdentifiers: InstitutionIdentifiers;
    userSettings?: UserSettings;
    /**
     * URL of client\'s server to redirect the PSU after completion of the consent authorisation.
     */
    redirectUrl: string;
    /**
     * Used to receive a oneTimeToken rather than a consentToken at the redirectUrl for additional security. This can only be used when the redirectUrl is set.
     */
    oneTimeToken?: boolean;
    vrpSetup: VRPSetupRequest;
}

