/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HostedAccountRequest } from './hostedAccountRequest';
import { UserSettings } from './userSettings';
import { InstitutionIdentifiers } from './institutionIdentifiers';


export interface CreateHostedConsentRequest { 
    /**
     * __Conditional__. Yapily Identifier for the `User` returned by the create user step POST /users. You must provide either a `userId` or `applicationUserId`.
     */
    userId?: string;
    /**
     * __Conditional__. Your own `User` reference. This field allows you to use your own unique references for individual users. Where the `User` reference doesn\'t have an associated Yapily `userId`, a new `userId` is created and linked to it. You must provide either a `userId` or `applicationUserId`.
     */
    applicationUserId?: string;
    institutionIdentifiers: InstitutionIdentifiers;
    userSettings?: UserSettings;
    /**
     * URL of your server to redirect the user after completion of the consent flow.
     */
    redirectUrl: string;
    /**
     * Used to receive a oneTimeToken rather than a consentToken at the redirectUrl for additional security.
     */
    oneTimeToken?: boolean;
    accountRequest?: HostedAccountRequest;
}

