/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CreditLineType } from './creditLineType';
import { Amount } from './amount';


/**
 * __Mandatory__. Details whether the account has access to a credit line from an `Institution`.
 */
export interface CreditLine { 
    type?: CreditLineType;
    creditLineAmount?: Amount;
}
export namespace CreditLine {
}


