/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Provides details on the currrency exchange.
 */
export interface CurrencyExchange { 
    /**
     * Currency from which an amount is to be converted.
     */
    sourceCurrency?: string;
    /**
     * Currency to which an amount is to be converted.
     */
    targetCurrency?: string;
    /**
     * The currency in which the rate of exchange is expressed in a currency exchange. In the example 1GBP = xxxCUR, the unit currency is GBP.
     */
    unitCurrency?: string;
    /**
     * The factor used for conversion of an amount from one currency to another. This reflects the price at which one currency was bought with another currency.
     */
    exchangeRate?: number;
}

