/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Indicates the outcome of the delete request.
 */
export type DeleteStatusEnum = 'SUCCESS' | 'FAILED';

export const DeleteStatusEnum = {
    Success: 'SUCCESS' as DeleteStatusEnum,
    Failed: 'FAILED' as DeleteStatusEnum
};

