/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ScaMethod } from './scaMethod';
import { AuthorisationStatus } from './authorisationStatus';
import { FeatureEnum } from './featureEnum';


export interface EmbeddedAccountAuthorisationResponse { 
    /**
     * Unique identifier for the embedded account authorisation request.
     */
    id?: string;
    /**
     * The `User` that the authorisation request was created for.
     */
    userUuid?: string;
    /**
     * The user-friendly reference to the `User` that the authorisation request was created for.
     */
    applicationUserId?: string;
    referenceId?: string;
    /**
     * The `Institution` the authorisation request was sent to.
     */
    institutionId?: string;
    status?: AuthorisationStatus;
    /**
     * Date and time the embedded authorisation was created by the application user.
     */
    createdAt?: string;
    /**
     * When performing a transaction query using the consent, this is the earliest date of transaction records that can be retrieved.
     */
    transactionFrom?: string;
    /**
     * When performing a transaction query using the consent, this is the latest date of transaction records that can be retrieved.
     */
    transactionTo?: string;
    /**
     * Date and time the embedded authorisation expires. Re-authorisation is needed to retain access.
     */
    expiresAt?: string;
    /** @deprecated */
    timeToExpireInMillis?: number;
    timeToExpire?: string;
    /**
     * The set of features the consent provides access to.
     */
    featureScope?: Set<FeatureEnum>;
    /**
     * Represents the authorisation to gain access to the requested features. Required to access account information.
     */
    consentToken?: string;
    /**
     * Correlation ID used when handshaking with a new institution via OAuth2 registration.
     */
    state?: string;
    /**
     * Date and time the request was authorised by the `Institution`.
     */
    authorizedAt?: string;
    /**
     * Identification of the consent at the `Institution`.
     */
    institutionConsentId?: string;
    authorisationUrl?: string;
    /**
     * The URL link for the QR code that may be scanned via a mobile device to make an authorisation redirect to the bank (authURL encoded).
     */
    qrCodeUrl?: string;
    /**
     * List of `SCA methods` that the `Institution` supports and are available for selection.
     */
    scaMethods?: Array<ScaMethod>;
    selectedScaMethod?: ScaMethod;
}
export namespace EmbeddedAccountAuthorisationResponse {
}


