/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Details of the transaction, identified by Yapily data services.
 */
export interface EnrichedTransaction { 
    /**
     * Unique identifier of the transaction
     */
    transactionId?: string;
    /**
     * Information for the transaction
     */
    transactionInformation?: string;
    /**
     * Monetary amount.
     */
    amount?: number;
    /**
     * The `Institution` that the transaction is sent to.
     */
    institution?: string;
    /**
     * Date and time of when a transaction entry occured and was posted to the account servicer\'s books.
     */
    bookingDateTime?: string;
}

