/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Details of the merchant, identified by Yapily data services.
 */
export interface EnrichmentMerchant { 
    /**
     * The name of the indivdual merchant involved in the transaction e.g. (TESCO Petrol).
     */
    merchantName?: string;
    /**
     * The parent organisation that the merchant belongs to e.g. (TESCO).
     */
    parentGroup?: string;
}

