/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TerminatedTransactionStream } from './terminatedTransactionStream';
import { TransactionStream } from './transactionStream';


/**
 * Details of income and expenditure streams, identified by Yapily data services.
 */
export interface EnrichedWrapper { 
    /**
     * Lists all possible income streams identified for the `Application User`.
     */
    incomeStreams: Array<TransactionStream>;
    /**
     * Lists all possible expenditure streams identified for the `Application User`.
     */
    expenditureStreams: Array<TransactionStream>;
    /**
     * A list of terminated transaction income streams
     */
    recentlyTerminatedIncomeStreams: Array<TerminatedTransactionStream>;
    /**
     * A list of terminated transaction expenditure streams
     */
    recentlyTerminatedExpenditureStreams: Array<TerminatedTransactionStream>;
}

