/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Categorisation } from './categorisation';
import { EnrichmentMerchant } from './enrichmentMerchant';
import { TransactionHash } from './transactionHash';


/**
 * Enriched data that has been derived by Yapily using it\'s data processing and machine learning techniques.
 */
export interface Enrichment { 
    categorisation?: Categorisation;
    transactionHash?: TransactionHash;
    /**
     * Cleaned version of the `Transaction Description` that removes miscellaneous, generic and unhelpful text.
     */
    cleansedDescription?: string;
    merchant?: EnrichmentMerchant;
    /**
     * The location of where the transaction took place.
     */
    location?: string;
    /**
     * A payment provider that manages (credit/debit) transactions between the `Institution` and the merchant.
     */
    paymentProcessor?: string;
    /**
     * The likely date and time on which the transaction took place. This is distinct from `Booking Date Time` which usually refers to the post-clearing value.
     */
    correctedDate?: string;
}

