/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type EnumError = 'MANDATORY' | 'INVALID_FORMAT';

export const EnumError = {
    Mandatory: 'MANDATORY' as EnumError,
    InvalidFormat: 'INVALID_FORMAT' as EnumError
};

