/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The environment type. <br><br>See [Institution Configuration](https://docs.yapily.com/pages/key-concepts/institutions/#configuration) for more information
 */
export type EnvironmentType = 'SANDBOX' | 'MOCK' | 'LIVE';

export const EnvironmentType = {
    Sandbox: 'SANDBOX' as EnvironmentType,
    Mock: 'MOCK' as EnvironmentType,
    Live: 'LIVE' as EnvironmentType
};

