/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InstitutionError } from './institutionError';


/**
 * Detailed information regarding the issue that was experienced during processing of the request
 */
export interface ErrorIssue { 
    /**
     * Category of the issue
     */
    type: string;
    /**
     * Code that uniquely identifies the type of issue
     */
    code: string;
    /**
     * Identfies the parameter / property within the request (headers, query parameters or body) that the issue relates to. For headers and query parameters, it refers to the parameter name. For the body, it refers to the JSONPath of the property
     */
    parameter?: string;
    /**
     * Human readable description of the issue that was experienced
     */
    message?: string;
    institutionError?: InstitutionError;
}

