/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RateTypeEnum } from './rateTypeEnum';


export interface ExchangeRateInformationResponse { 
    /**
     * __Mandatory__. The currency in which the rate of exchange is expressed in a currency exchange. In the example 1GBP = xxxCUR, the unit currency is `GBP`.
     */
    unitCurrency: string;
    /**
     * __Optional__. The factor used for conversion of an amount from one currency to another. This reflects the price at which one currency was bought with another currency.
     */
    rate?: number;
    rateType: RateTypeEnum;
    /**
     * __Optional__. The unique and unambiguous reference to the foreign exchange contract agreed between the initiating party/creditor and the debtor agent.
     */
    foreignExchangeContractReference?: string;
    exchangeRateExpiryDate?: string;
}
export namespace ExchangeRateInformationResponse {
}


