/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExtendConsentRequest { 
    /**
     * __Mandatory__. The time that the user confirmed access to their account information
     */
    lastConfirmedAt: string;
}

