/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Consent } from './consent';
import { FilterAndSort } from './filterAndSort';


export interface FilteredClientPayloadListConsent { 
    apiCall?: object;
    data?: Array<Consent>;
    nextCursorHash?: string;
    nextLink?: string;
    pagingMap?: { [key: string]: FilterAndSort; };
    totalCount?: number;
}

