/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FilterAndSort } from './filterAndSort';
import { AccountStatement } from './accountStatement';


export interface FilteredClientPayloadListAccountStatement { 
    apiCall?: object;
    data?: Array<AccountStatement>;
    nextCursorHash?: string;
    nextLink?: string;
    pagingMap?: { [key: string]: FilterAndSort; };
    totalCount?: number;
}

