/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FilterAndSort } from './filterAndSort';
import { PaymentResponse } from './paymentResponse';


export interface FilteredClientPayloadListPaymentResponse { 
    apiCall?: object;
    data?: Array<PaymentResponse>;
    nextCursorHash?: string;
    nextLink?: string;
    pagingMap?: { [key: string]: FilterAndSort; };
    totalCount?: number;
}

