/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FilterAndSort } from './filterAndSort';
import { Institution } from './institution';


export interface FilteredClientPayloadListInstitution { 
    apiCall?: object;
    data?: Array<Institution>;
    nextCursorHash?: string;
    nextLink?: string;
    pagingMap?: { [key: string]: FilterAndSort; };
    totalCount?: number;
}

