/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * __Mandatory__. Frequency for which the payment limits are enforced. Allowed values are [MONTHLY].
 */
export type FrequencyEnum = 'MONTHLY';

export const FrequencyEnum = {
    Monthly: 'MONTHLY' as FrequencyEnum
};

