/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FrequencyEnumExtended } from './frequencyEnumExtended';


/**
 * __Mandatory__. Defines the intervals at which payment should be made.
 */
export interface FrequencyRequest { 
    type: FrequencyEnumExtended;
    /**
     * __Conditional__. See [payment frequency](/guides/payments/payment-execution/periodic-payments/#payment-frequency) for more information
     */
    intervalWeek?: number;
    /**
     * __Conditional__. See [payment frequency](/guides/payments/payment-execution/periodic-payments/#payment-frequency) for more information
     */
    intervalMonth?: number;
    /**
     * __Conditional__. See [payment frequency](/guides/payments/payment-execution/periodic-payments/#payment-frequency) for more information
     */
    executionDay?: number;
}
export namespace FrequencyRequest {
}


