/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FrequencyEnumExtended } from './frequencyEnumExtended';


/**
 * __Mandatory__. Defines the intervals at which payment should be made.
 */
export interface FrequencyResponse { 
    frequencyType?: FrequencyEnumExtended;
    /**
     * The weekly intervals at which a payment will be made. e.g. 1 = Every months, 2 = Every 2 months.
     */
    intervalWeek?: number;
    /**
     * The monthly intervals at which a payment will be made. e.g. 1 = Every month, 2 = Every 2 months
     */
    intervalMonth?: number;
    /**
     * The day on which a payment will be made, according to the weekly or monthly interval.
     */
    executionDay?: number;
}
export namespace FrequencyResponse {
}


