/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Amount } from './amount';


/**
 * The fund confirmation object defining the details of the account and funds to be checked under the Variable Recurring Payment consent.
 */
export interface FundsConfirmationRequest { 
    /**
     * __Optional__. The payment reference or description. Limited to a maximum of 18 characters long.
     */
    reference?: string;
    paymentAmount: Amount;
}

