/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FundsAvailable { 
    /**
     * __Mandatory__. Indicates whether funds are available or not.
     */
    fundsAvailable: boolean;
    /**
     * __Mandatory__. Date and Time when the funds availability is checked.
     */
    fundsAvailableAt: string;
}

