/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetAccountsTransactionsCategorised200ResponseLinks } from './getAccountsTransactionsCategorised200ResponseLinks';
import { GetAccountsTransactionsCategorised200ResponseMeta } from './getAccountsTransactionsCategorised200ResponseMeta';
import { GetAccountsTransactionsCategorised200ResponseData } from './getAccountsTransactionsCategorised200ResponseData';


export interface GetAccountsTransactionsCategorised200Response { 
    meta?: GetAccountsTransactionsCategorised200ResponseMeta;
    data?: GetAccountsTransactionsCategorised200ResponseData;
    links?: GetAccountsTransactionsCategorised200ResponseLinks;
}

