/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetAccountsTransactionsCategorised200ResponseDataTransactionsInnerTransactionAmount } from './getAccountsTransactionsCategorised200ResponseDataTransactionsInnerTransactionAmount';


export interface GetAccountsTransactionsCategorised200ResponseDataTransactionsInnerBalance { 
    type?: string;
    balanceAmount?: GetAccountsTransactionsCategorised200ResponseDataTransactionsInnerTransactionAmount;
}

