/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetAccountsTransactionsCategorised200ResponseDataTransactionsInner } from './getAccountsTransactionsCategorised200ResponseDataTransactionsInner';


export interface GetAccountsTransactionsCategorised200ResponseData { 
    transactions?: Array<GetAccountsTransactionsCategorised200ResponseDataTransactionsInner>;
}

