/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetBulkPaymentStatus200ResponseDataStatusDetails { 
    /**
     * Bulk file status. Enum: `COMPLETED` `PENDING` `FAILED` `UNKNOWN`
     */
    status?: string;
    updatedAt?: string;
}

