/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetBulkPaymentStatus200ResponseDataStatusDetails } from './getBulkPaymentStatus200ResponseDataStatusDetails';


export interface GetBulkPaymentStatus200ResponseData { 
    /**
     * Unique identifier of the Bulk Payment
     */
    id?: string;
    /**
     * Identification of the consent.
     */
    consentId?: string;
    statusDetails?: GetBulkPaymentStatus200ResponseDataStatusDetails;
    createdAt?: string;
}

