/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetBulkPaymentStatus200ResponseMeta } from './getBulkPaymentStatus200ResponseMeta';
import { GetCategoriesResponse } from './getCategoriesResponse';


export interface GetCategorisationAccountType200Response { 
    meta?: GetBulkPaymentStatus200ResponseMeta;
    data?: GetCategoriesResponse;
}

