/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RegisteredWebhookWithStatus } from './registeredWebhookWithStatus';


export interface GetRegisteredWebhooks200ResponseData { 
    active?: Array<RegisteredWebhookWithStatus>;
}

