/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GetWebhookEventsCategories200ResponseData } from './getWebhookEventsCategories200ResponseData';
import { Metadata } from './metadata';


export interface GetWebhookEventsCategories200Response { 
    metadata?: Metadata;
    data?: GetWebhookEventsCategories200ResponseData;
}

