/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PayerDetailsResponse } from './payerDetailsResponse';
import { PaymentContextTypeResponse } from './paymentContextTypeResponse';
import { AmountDetailsResponse } from './amountDetailsResponse';
import { PayeeDetailsResponse } from './payeeDetailsResponse';
import { PaymentTypeResponse } from './paymentTypeResponse';


/**
 * Details of the payment.
 */
export interface HostedPaymentResponseDetails { 
    /**
     * A unique identifier provided to identify the payment. This can be any alpha-numeric string but is limited to a maximum of 35 characters.
     */
    paymentIdempotencyId?: string;
    /**
     * The payment reference or description. Limited to a maximum of 18 characters for UK institutions.
     */
    reference?: string;
    contextType?: PaymentContextTypeResponse;
    type?: PaymentTypeResponse;
    payee?: PayeeDetailsResponse;
    payer?: PayerDetailsResponse;
    amountDetails?: AmountDetailsResponse;
    /**
     * The date that the payment is due.
     */
    paymentDueDate?: string;
}
export namespace HostedPaymentResponseDetails {
}


