/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PayerDetailsResponse } from './payerDetailsResponse';
import { PaymentContextTypeResponse } from './paymentContextTypeResponse';
import { AmountDetailsResponse } from './amountDetailsResponse';
import { PayeeDetailsResponse } from './payeeDetailsResponse';
import { PaymentTypeResponse } from './paymentTypeResponse';


export interface HostedPaymentRequestDetailsLink { 
    /**
     * The payment reference or description. Limited to a maximum of 18 characters for UK institutions.
     */
    reference?: string;
    contextType?: PaymentContextTypeResponse;
    type?: PaymentTypeResponse;
    payee?: PayeeDetailsResponse;
    payer?: PayerDetailsResponse;
    amountDetails?: AmountDetailsResponse;
    /**
     * The date that the payment is due. Displayed to the end user in the payment summary screen.
     */
    paymentDueDate?: string;
}
export namespace HostedPaymentRequestDetailsLink {
}


