/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HostedAccountRequestDetailsResponse } from './hostedAccountRequestDetailsResponse';
import { InstitutionIdentifiersResponse } from './institutionIdentifiersResponse';
import { UserSettings } from './userSettings';


export interface HostedConsentRequestResponse { 
    /**
     * Unique Id of the consent request.
     */
    consentRequestId?: string;
    /**
     * Unique Id for the `User` assigned by Yapily.
     */
    userId?: string;
    /**
     * Your reference to the `User`.
     */
    applicationUserId?: string;
    /**
     * Unique Id of the `Application` the user is associated with.
     */
    applicationId?: string;
    institutionIdentifiers?: InstitutionIdentifiersResponse;
    userSettings?: UserSettings;
    /**
     * URL of consent server to redirect the user after completion of the consent flow.
     */
    redirectUrl?: string;
    accountRequestDetails?: HostedAccountRequestDetailsResponse;
    /**
     * The URL of Hosted UI page for the applicationId which initiates the user journey for the consent. <br> URL would be appended with authToken, applicationId and userSettings.
     */
    hostedUrl?: string;
    /**
     * The date and time at which the consent was created.
     */
    createdAt?: string;
    /**
     * The date and time at which the auth Token will expire.
     */
    authorisationExpiresAt?: string;
}

