/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The payment amount and currency
 */
export interface HostedAmountDetails { 
    /**
     * The payment amount
     */
    amountToPay: number;
    /**
     * The [ISO 4217](https://www.xe.com/iso4217.php) currency code
     */
    currency: string;
}

