/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HostedPaymentStatusDetails } from './hostedPaymentStatusDetails';
import { HostedVrpPayerResponse } from './hostedVrpPayerResponse';
import { Amount } from './amount';
import { HostedVrpRefundAccount } from './hostedVrpRefundAccount';
import { Payee } from './payee';
import { PaymentRisk } from './paymentRisk';


export interface HostedVRPPaymentResponse { 
    id?: string;
    paymentIdempotencyId?: string;
    amount?: Amount;
    /**
     * __Optional__. The payment reference or description. Limited to a maximum of 18 characters long.
     */
    reference?: string;
    payee?: Payee;
    payer?: HostedVrpPayerResponse;
    refundAccount?: HostedVrpRefundAccount;
    risk?: PaymentRisk;
    /**
     * The Unique Identifier provided by TPP in the Payment request to identify the payment.
     */
    paymentLifecycleId?: string;
    expectedExecutionTime?: string;
    expectedSettlementTime?: string;
    institutionPaymentId?: string;
    statusDetails?: HostedPaymentStatusDetails;
}

