/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Address } from './address';
import { HostedVrpAccountIdentification } from './hostedVrpAccountIdentification';


/**
 * __Conditional__. Details of the benefactor [person or business].
 */
export interface HostedVrpPayerResponse { 
    /**
     * The account holder name of the Payer.
     */
    name?: string;
    /**
     * __Mandatory__. The account identifications that identify the `Payer` bank account.
     */
    accountIdentifications: Set<HostedVrpAccountIdentification>;
    address?: Address;
}

