/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HostedNonSweepingPeriodicLimits } from './hostedNonSweepingPeriodicLimits';
import { Amount } from './amount';


/**
 * The restrictions and limits for payments executed under the VRP consent
 */
export interface HostedVRPLimits { 
    periodicLimits?: Array<HostedNonSweepingPeriodicLimits>;
    /**
     * __Optional__. Max amount that can be submitted per payment.
     */
    maxAmountPerPayment?: Amount;
    /**
     * __Optional__. Max cumulative amount that can be submitted under this consent.
     */
    maxCumulativeAmount?: Amount;
    /**
     * __Optional__. Max number of payments that can be submitted under this consent.
     */
    maxCumulativeNumberOfPayments?: number;
    /**
     * Indicates if the user edited the control parameters during authorisation
     */
    editedByUser?: boolean;
}

