/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddressTypeEnum } from './addressTypeEnum';


export interface IdentityAddress { 
    addressLines?: Array<string>;
    city?: string;
    postalCode?: string;
    country?: string;
    streetName?: string;
    buildingNumber?: string;
    type?: AddressTypeEnum;
    county?: string;
}
export namespace IdentityAddress {
}


