/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Payer } from './payer';
import { Payee } from './payee';


/**
 * __Mandatory__. The payment initiation object defining the details of the payment under the Variable Recurring Payment consent.
 */
export interface InitiationDetails { 
    /**
     * __Optional__. The payment reference or description. Limited to a maximum of 18 characters long.
     */
    reference?: string;
    payer?: Payer;
    payee?: Payee;
}

