/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Raw error details provided by the `Institution`, when it was the error source.
 */
export interface InstitutionError { 
    /**
     * Textual description of the `Institution` error.
     */
    errorMessage?: string;
    /**
     * Numeric HTTP status code associated with the `Institution` error.
     */
    httpStatusCode?: number;
}

