/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Specifies the institution selected for making the payment.
 */
export interface InstitutionIdentifiersResponse { 
    /**
     * Yapily identifier which identifies the `Institution` the payment request is sent to.
     */
    institutionId?: string;
    /**
     * 2 letter ISO Country code of the `Institution` the payment request is sent to.
     */
    institutionCountryCode?: string;
}

