/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IsoCodeDetails } from './isoCodeDetails';


/**
 * Defines the underlying transaction type (e.g. Card or Debit Transactions, Loans or Mortages). <br><br> Conforms to `ISO` standards - ISO 20022.
 */
export interface IsoBankTransactionCode { 
    domainCode?: IsoCodeDetails;
    familyCode?: IsoCodeDetails;
    subFamilyCode?: IsoCodeDetails;
}

