/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Details of a new user to be created for the application.
 */
export interface NewApplicationUser { 
    /**
     * __Optional__. The unique identifier of the `Application User` assigned by the Application Owner.
     */
    applicationUserId?: string;
    /**
     * __Deprecated__. A non-unique reference Id for the `Application User`.
     */
    referenceId?: string;
}

