/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NonSweepingControlParameters } from './nonSweepingControlParameters';
import { RedirectRequest } from './redirectRequest';
import { ComplianceData } from './complianceData';
import { InitiationDetails } from './initiationDetails';


export interface NonSweepingAuthorisationRequest { 
    /**
     * This is the Yapily user identifier for the user returned by the create user step POST ../users
     */
    userId?: string;
    /**
     * A client\'s own user reference. If the client wants to work with their own unique references for individual PSUs then they can use the applicationUserId property to provide that value. Where Yapily does not already have a Yapily userId that matches the supplied applicationUserId, then a new Yapily userId is created automatically and linked to the applicationUserId value.  Clients can then use either their own applicationUserId or the Yapily userId to reference the same user in future calls.
     */
    applicationUserId?: string;
    /**
     * Extra parameters the TPP may want to get forwarded in the callback request after the PSU redirect.
     */
    forwardParameters?: Array<string>;
    /**
     * __Optional__. The payment context code. Allowed values are [BILL_IN_ADVANCE, BILL_IN_ARREARS, ECOMMERCE_MERCHANT, FACE_TO_FACE_POS, TRANSFER_TO_SELF,TRANSFER_TO_THIRD_PARTY, PISP_PAYEE ].
     */
    contextType?: string;
    /**
     * __Mandatory__. The reference to the `Institution` which identifies which institution the authorisation request is sent to.
     */
    institutionId: string;
    /**
     * __Optional__. The server to redirect the user to after the user complete the authorisation at the `Institution`. <br><br>See [Using a callback (Optional)](https://docs.yapily.com/knowledge/callback_url/#using-a-callback-optional) for more information.
     */
    callback?: string;
    redirect?: RedirectRequest;
    /**
     * __Conditional__. Used to receive a `oneTimeToken` rather than a `consentToken` at the `callback` for additional security. This can only be used when the `callback` is set. <br><br>See [Using a callback with an OTT (Optional)](https://docs.yapily.com/knowledge/callback_url/#using-a-callback-with-an-ott-optional) for more information.
     */
    oneTimeToken?: boolean;
    controlParameters: NonSweepingControlParameters;
    initiationDetails: InitiationDetails;
    complianceData?: ComplianceData;
}

