/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The request body containing the `OneTimeTokenRequest` json payload
 */
export interface OneTimeTokenRequest { 
    /**
     * __Mandatory__. The one time token to exchange for a consent token.
     */
    oneTimeToken: string;
}

