/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FilterAndSort } from './filterAndSort';
import { Next } from './next';


export interface Pagination { 
    totalCount?: number;
    self?: FilterAndSort;
    next?: Next;
}

