/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Address } from './address';
import { AccountIdentification } from './accountIdentification';


/**
 * __Mandatory__. Details of the beneficiary [person or business].
 */
export interface Payee { 
    /**
     * __Mandatory__. The account holder name of the beneficiary.
     */
    name: string;
    /**
     * __Mandatory__. The account identifications that identify the `Payee` bank account.
     */
    accountIdentifications: Set<AccountIdentification>;
    /**
     * __Optional__. The payee account type. <br><br>Allowed values: BUSINESS, BUSINESS_SAVING, CHARITY, COLLECTION, CORPORATE, E_WALLET, GOVERNMENT, INVESTMENT, INVESTMENT_ISA, JOINT_PERSONAL, PENSION, PERSONAL, PERSONAL_SAVING, PREMIER, WEALTH .
     */
    accountType?: string;
    address?: Address;
    /**
     * __Optional__. The merchant ID is a unique code provided by the payment processor to the merchant.
     */
    merchantId?: string;
    /**
     * __Optional__. The category code of the merchant in case the `Payee` is a business. Specified as a 3-letter ISO 18245 code.
     */
    merchantCategoryCode?: string;
}

