/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountIdentification } from './accountIdentification';


/**
 * __Mandatory__. Details of the beneficiary [person or business].
 */
export interface PayeeDetails { 
    /**
     * __Mandatory__. The account holder name of the beneficiary.
     */
    name: string;
    /**
     * __Mandatory__. The account identifications that identify the `Payee` bank account.
     */
    accountIdentifications: Set<AccountIdentification>;
    /**
     * __Conditional__. The 2-letter ISO 3166 country code for the address. <br><br>An `Institution` may require you to specify the `country` when used in the context of the `Payee` to be able to make a payment
     */
    country: string;
}

