/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaymentIsoStatus } from './paymentIsoStatus';
import { PaymentStatus } from './paymentStatus';
import { MultiAuthorisation } from './multiAuthorisation';


export interface PaymentStatusDetails { 
    status?: PaymentStatus;
    statusReason?: string;
    statusReasonDescription?: string;
    statusUpdateDate?: string;
    multiAuthorisationStatus?: MultiAuthorisation;
    isoStatus?: PaymentIsoStatus;
}
export namespace PaymentStatusDetails {
}


