/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The payment context code.
 */
export type PaymentContextTypeResponse = 'BILL' | 'GOODS' | 'SERVICES' | 'OTHER' | 'PERSON_TO_PERSON';

export const PaymentContextTypeResponse = {
    Bill: 'BILL' as PaymentContextTypeResponse,
    Goods: 'GOODS' as PaymentContextTypeResponse,
    Services: 'SERVICES' as PaymentContextTypeResponse,
    Other: 'OTHER' as PaymentContextTypeResponse,
    PersonToPerson: 'PERSON_TO_PERSON' as PaymentContextTypeResponse
};

