/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RequestConstraints } from './requestConstraints';
import { PaymentTypeOfConstraints } from './paymentTypeOfConstraints';


export interface PaymentConstraintsResponse { 
    /**
     * The id to represent the `Institution`.
     */
    institutionId: string;
    /**
     * 2 letter ISO Country code of the `Institution`.
     */
    institutionCountryCode?: string;
    /**
     * Define the applicable API end point.
     */
    endpointPath?: string;
    /**
     * Https Method for the endpoint.
     */
    endpointMethod?: string;
    paymentType: PaymentTypeOfConstraints;
    request: RequestConstraints;
}
export namespace PaymentConstraintsResponse {
}


