/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * __Optional__. The payment context code. This defaults to `OTHER` if not specified.
 */
export type PaymentContextType = 'BILL' | 'GOODS' | 'SERVICES' | 'OTHER' | 'PERSON_TO_PERSON' | 'BILL_IN_ADVANCE' | 'BILL_IN_ARREARS' | 'ECOMMERCE_MERCHANT' | 'FACE_TO_FACE_POS' | 'TRANSFER_TO_SELF' | 'TRANSFER_TO_THIRD_PARTY' | 'PISP_PAYEE';

export const PaymentContextType = {
    Bill: 'BILL' as PaymentContextType,
    Goods: 'GOODS' as PaymentContextType,
    Services: 'SERVICES' as PaymentContextType,
    Other: 'OTHER' as PaymentContextType,
    PersonToPerson: 'PERSON_TO_PERSON' as PaymentContextType,
    BillInAdvance: 'BILL_IN_ADVANCE' as PaymentContextType,
    BillInArrears: 'BILL_IN_ARREARS' as PaymentContextType,
    EcommerceMerchant: 'ECOMMERCE_MERCHANT' as PaymentContextType,
    FaceToFacePos: 'FACE_TO_FACE_POS' as PaymentContextType,
    TransferToSelf: 'TRANSFER_TO_SELF' as PaymentContextType,
    TransferToThirdParty: 'TRANSFER_TO_THIRD_PARTY' as PaymentContextType,
    PispPayee: 'PISP_PAYEE' as PaymentContextType
};

