/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Specifies which of the [payment types](https://docs.yapily.com/pages/key-concepts/payments/payment-execution/intro-to-payment-execution/#payment-types) to execute.<br>
 */
export type PaymentTypeResponse = 'DOMESTIC_PAYMENT' | 'DOMESTIC_INSTANT_PAYMENT' | 'DOMESTIC_VARIABLE_RECURRING_PAYMENT' | 'DOMESTIC_SCHEDULED_PAYMENT' | 'DOMESTIC_PERIODIC_PAYMENT' | 'INTERNATIONAL_PAYMENT' | 'INTERNATIONAL_SCHEDULED_PAYMENT' | 'INTERNATIONAL_PERIODIC_PAYMENT';

export const PaymentTypeResponse = {
    DomesticPayment: 'DOMESTIC_PAYMENT' as PaymentTypeResponse,
    DomesticInstantPayment: 'DOMESTIC_INSTANT_PAYMENT' as PaymentTypeResponse,
    DomesticVariableRecurringPayment: 'DOMESTIC_VARIABLE_RECURRING_PAYMENT' as PaymentTypeResponse,
    DomesticScheduledPayment: 'DOMESTIC_SCHEDULED_PAYMENT' as PaymentTypeResponse,
    DomesticPeriodicPayment: 'DOMESTIC_PERIODIC_PAYMENT' as PaymentTypeResponse,
    InternationalPayment: 'INTERNATIONAL_PAYMENT' as PaymentTypeResponse,
    InternationalScheduledPayment: 'INTERNATIONAL_SCHEDULED_PAYMENT' as PaymentTypeResponse,
    InternationalPeriodicPayment: 'INTERNATIONAL_PERIODIC_PAYMENT' as PaymentTypeResponse
};

