/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Amount } from './amount';
import { FrequencyRequest } from './frequencyRequest';


/**
 * __Conditional__. Used to specify properties to define a periodic payment. <br><br>Must be specified when the payment `type` is one of the following:<ul>     <li><code>DOMESTIC_PERIODIC_PAYMENT</code></li>     <li><code>INTERNATIONAL_PERIODIC_PAYMENT</code></li></ul>
 */
export interface PeriodicPaymentRequest { 
    frequency: FrequencyRequest;
    /**
     * __Conditional__. Defines the total number of payments to be made.<br><br>This is required if `finalPaymentDateTime` is not specified and it is intended for the periodic payment have a fixed amount of payments.
     */
    numberOfPayments?: number;
    /**
     * __Conditional__. Defines when to start the recurring payment date and time. Specify this if you want the first payment to start on a different day than what the frequency object defines.
     */
    nextPaymentDateTime?: string;
    nextPaymentAmount?: Amount;
    /**
     * __Conditional__. Defines the final payment date and time. To create an open-ended periodic payment, do not specify this property.
     */
    finalPaymentDateTime?: string;
    finalPaymentAmount?: Amount;
}

