/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PostAccountsAccountIdTransactionsCategorisationRequest { 
    /**
     * _Mandatory_, ISO 3166-1 alpha-2 two-letter country codes e.g. GB
     */
    countryCode: string;
    /**
     * __Mandatory__. Allowed values are `consumer` and `business`.
     */
    categorisationType: string;
    /**
     * __Optional__. Returned transactions will be on or after this date (yyyy-MM-dd\'T\'HH:mm:ss.SSSZ). 
     */
    from?: string;
    /**
     * __Optional__. Returned transactions will be on or before this date (yyyy-MM-dd\'T\'HH:mm:ss.SSSZ).
     */
    before?: string;
}

