/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RedirectRequest } from './redirectRequest';


export interface PreAuthorisationRequest { 
    userUuid?: string;
    /**
     * __Conditional__. The user-friendly reference to the `User` that will authorise the authorisation request. If a `User` with the specified `applicationUserId` exists, it will be used otherwise, a new `User` with the specified `applicationUserId` will be created and used. Either the `userUuid` or `applicationUserId` must be provided.
     */
    applicationUserId?: string;
    /**
     * Extra parameters to be forwarded in the redirect back to the client after the user authorisation flow has been completed.
     */
    forwardParameters?: Array<string>;
    /**
     * __Mandatory__. The reference to the `Institution` which identifies which institution the authorisation request is sent to.
     */
    institutionId: string;
    /**
     * __Optional__. The server to redirect the user to after the user complete the authorisation at the `Institution`. <br><br>See [Using a callback (Optional)](https://docs.yapily.com/pages/knowledge/yapily-concepts/callback_url/#using-a-callback-optional) for more information.
     */
    callback?: string;
    redirect?: RedirectRequest;
    /**
     * __Conditional__. Used to receive a `oneTimeToken` rather than a `consentToken` at the `callback` for additional security. This can only be used when the `callback` is set. <br><br>See [Using a callback with an OTT (Optional)](https://docs.yapily.com/pages/knowledge/yapily-concepts/callback_url/#using-a-callback-with-an-ott-optional) for more information.
     */
    oneTimeToken?: boolean;
    /**
     * __Mandatory__. Defines the scope of the pre-authorisation request.
     */
    scope: string;
}

