/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * __Mandatory__. The type used to complete the currency exchange.
 */
export type RateTypeEnum = 'ACTUAL' | 'AGREED' | 'INDICATIVE';

export const RateTypeEnum = {
    Actual: 'ACTUAL' as RateTypeEnum,
    Agreed: 'AGREED' as RateTypeEnum,
    Indicative: 'INDICATIVE' as RateTypeEnum
};

