/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Payer } from './payer';
import { ProprietaryBankTransactionCode } from './proprietaryBankTransactionCode';
import { Merchant } from './merchant';
import { AddressDetails } from './addressDetails';
import { TransactionBalance } from './transactionBalance';
import { Amount } from './amount';
import { IsoBankTransactionCode } from './isoBankTransactionCode';
import { TransactionChargeDetails } from './transactionChargeDetails';
import { CurrencyExchange } from './currencyExchange';
import { TransactionStatusEnum } from './transactionStatusEnum';
import { StatementReference } from './statementReference';
import { Payee } from './payee';


export interface RealTimeTransaction { 
    id?: string;
    date?: string;
    bookingDateTime?: string;
    valueDateTime?: string;
    status?: TransactionStatusEnum;
    transactionAmount?: Amount;
    grossAmount?: Amount;
    currencyExchange?: CurrencyExchange;
    chargeDetails?: TransactionChargeDetails;
    reference?: string;
    statementReferences?: Array<StatementReference>;
    description?: string;
    transactionInformation?: Array<string>;
    addressDetails?: AddressDetails;
    isoBankTransactionCode?: IsoBankTransactionCode;
    proprietaryBankTransactionCode?: ProprietaryBankTransactionCode;
    balance?: TransactionBalance;
    payeeDetails?: Payee;
    payerDetails?: Payer;
    merchant?: Merchant;
    supplementaryData?: object;
}
export namespace RealTimeTransaction {
}


