/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * __Optional__. The server to redirect the user to after the user complete the authorisation at the `Institution`.
 */
export interface RedirectRequest { 
    /**
     * __Mandatory__.Successful redirect after the user complete the authorisation at the `Institution`.
     */
    url: string;
}

