/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RegisterWebhookRequestCallbackUrl } from './registerWebhookRequestCallbackUrl';


export interface RegisterWebhookRequest { 
    /**
     * user application id
     */
    applicationId: string;
    categories: Array<string>;
    callbackUrl: RegisterWebhookRequestCallbackUrl;
    metadata?: { [key: string]: string; };
}

