/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RegisteredWebhookCallbackUrl } from './registeredWebhookCallbackUrl';


export interface RegisteredWebhook { 
    /**
     * the UUID of the registered webhook, used to update or remove the webhook
     */
    id?: string;
    /**
     * user applicaiton id
     */
    applicationId?: string;
    categories?: Array<string>;
    callbackUrl?: RegisteredWebhookCallbackUrl;
    metadata?: { [key: string]: string; };
}

