/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RegisterWebhookRequestCallbackUrlBackup } from './registerWebhookRequestCallbackUrlBackup';
import { RegisteredWebhookCallbackUrlMain } from './registeredWebhookCallbackUrlMain';


export interface RegisteredWebhookCallbackUrl { 
    main?: RegisteredWebhookCallbackUrlMain;
    backup?: RegisterWebhookRequestCallbackUrlBackup;
}

