/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * primary webhook url used to send events to
 */
export interface RegisterWebhookRequestCallbackUrlMain { 
    url: string;
}

