/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Schema } from './schema';


/**
 * Object defining the constraints rules applicable for a given requests.
 */
export interface RequestConstraints { 
    headers?: Schema;
    body: Schema;
}

