/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Type } from './type';


/**
 * __Conditional__. Used to update the authorisation with the sca method of the user\'s choice for the `Institution` that uses the embedded authorisation flow. If the user has multiple sca methods configured, the `Institution` will allow the user to select from each of these options. <br><br>When the user has multiple sca methods for the `Institution`, this is the second step required in the embedded authorisation flow to authorise the `Consent`.
 */
export interface ScaMethod { 
    /**
     * __Mandatory__. The id of the sca method provided by the `Institution`
     */
    id: string;
    type?: Type;
    /**
     * __Optional__. A description of the sca method if provided by the `Institution`
     */
    description?: string;
    /**
     * Additional information from the institution to provide to the PSU to help with the selected SCA method. The language is determined by the institution and may vary.
     */
    information?: string;
    /**
     * Data from the institution to provide to the PSU to complete authorisation. The language is determined by the institution and may vary.
     */
    data?: Array<string>;
}
export namespace ScaMethod {
}


