/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type SchemaType = 'array' | 'boolean' | 'integer' | 'number' | 'object' | 'string';

export const SchemaType = {
    Array: 'array' as SchemaType,
    Boolean: 'boolean' as SchemaType,
    Integer: 'integer' as SchemaType,
    Number: 'number' as SchemaType,
    Object: 'object' as SchemaType,
    String: 'string' as SchemaType
};

