/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SearchApplicationsPublicFilterValuesParameter { 
    /**
     * Sub-application ids to filter the results for. If provided, the results will only include sub-applications with the given ids. Non-existent ids will be ignored.
     */
    applicationIds?: Array<string>;
    /**
     * The number of results to skip.
     */
    offset?: number;
    /**
     * The maximum number of results to return.
     */
    limit?: number;
    /**
     * The field to sort the results by.<br><br>Possible values:<ul><li>`last_updated` (ascending)</li><li>`-last_updated` (descending)</li><li>`name` (ascending)</li><li>`-name` (descending)</li><li>`uuid` (ascending)</li><li>`-uuid` (descending)</li></ul>
     */
    sort?: string;
}

