/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PaymentContextType } from './paymentContextType';
import { Amount } from './amount';


/**
 * __Mandatory__. The payment request object defining the details of the payment for execution under the Variable Recurring Payment consent.
 */
export interface SubmissionRequest { 
    /**
     * __Mandatory__. A unique identifier that you must provide to identify the payment. This can be any alpha-numeric string but is limited to a maximum of 35 characters.
     */
    paymentIdempotencyId: string;
    /**
     * __Mandatory__. Chosen authentication method for submission step. Allowed values are [SCA_REQUIRED, SCA_NOT_REQUIRED].
     */
    psuAuthenticationMethod: string;
    contextType?: PaymentContextType;
    paymentAmount: Amount;
}
export namespace SubmissionRequest {
}


