/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Payer } from './payer';
import { SweepingControlParameters } from './sweepingControlParameters';
import { AuthorisationStatus } from './authorisationStatus';
import { FeatureEnum } from './featureEnum';
import { InitiationDetails } from './initiationDetails';


export interface SweepingAuthorisationResponse { 
    id?: string;
    /**
     * This is the Yapily user identifier for the user returned by the create user step POST ../users
     */
    userId?: string;
    /**
     * A client\'s own user reference. If the client wants to work with their own unique references for individual PSUs then they can use the applicationUserId property to provide that value. Where Yapily does not already have a Yapily userId that matches the supplied applicationUserId, then a new Yapily userId is created automatically and linked to the applicationUserId value.  Clients can then use either their own applicationUserId or the Yapily userId to reference the same user in future calls.
     */
    applicationUserId?: string;
    /**
     * The reference to the Institution which identifies which institution the authorisation request is sent to.
     */
    institutionId?: string;
    status?: AuthorisationStatus;
    createdAt?: string;
    /**
     * __Optional__. Used to granularly specify the set of features that the user will give their consent for when requesting access to their account information. Depending on the `Institution`, this may also populate a consent screen which list these scopes before the user authorises.<br><br>This endpoint accepts allow all [Financial Data Features](/guides/financial-data/features/#feature-list) that the `Institution` supports.To find out which scopes an `Institution` supports, check [GET Institution](./#get-institution).
     */
    featureScope?: Set<FeatureEnum>;
    /**
     * The `consent-token` containing the user\'s authorisation to make the payment request.
     */
    consentToken?: string;
    state?: string;
    authorizedAt?: string;
    /**
     * Identification of the consent at the Institution.
     */
    institutionConsentId?: string;
    authorisationUrl?: string;
    qrCodeUrl?: string;
    controlParameters?: SweepingControlParameters;
    payer?: Payer;
    initiationDetails?: InitiationDetails;
}
export namespace SweepingAuthorisationResponse {
}


