/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnrichedTransaction } from './enrichedTransaction';
import { TransactionSchedule } from './transactionSchedule';


/**
 * Terminated transaction stream generated as part of the financial profile for a User.
 */
export interface TerminatedTransactionStream { 
    /**
     * The name of the TransactionStream
     */
    name?: string;
    /**
     * A list of Transactions from the transaction stream.
     */
    transactions?: Array<EnrichedTransaction>;
    transactionSchedule?: TransactionSchedule;
    /**
     * The consistency of the transaction.  This is a number between 0 and 1 with 1 being the most consistent schedule.
     */
    scheduleConsistencyScore?: number;
    /**
     * When is the transaction expected to occur next.
     */
    nextExpectedTransactionDate?: string;
    /**
     * When is the first recorded transaction date
     */
    earliestTransactionDate?: string;
    /**
     * When is the most recent transaction date
     */
    mostRecentTransactionDate?: string;
    /**
     * The consistency of the amount of the transaction.  This is a number between 0 and 1 with 1 being the most consistent amount.
     */
    amountConsistencyScore?: number;
    /**
     * The average amount of the transaction stream
     */
    averageAmount?: number;
    /**
     * Missed transactions of transaction stream
     */
    missedTransactions?: number;
}

