/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AccountIdentificationType } from './accountIdentificationType';


export interface TransactionPayeeDetailsAccountIdentificationsInner { 
    /**
     * Describes the format of the account.
     */
    type?: AccountIdentificationType;
    /**
     * The value associated with the account identification type.
     */
    identification?: string;
}
export namespace TransactionPayeeDetailsAccountIdentificationsInner {
}


