/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Amount } from './amount';


/**
 * Details the charges that will apply to the transaction.
 */
export interface TransactionChargeDetails { 
    chargeAmount?: Amount;
}

