/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransactionPayeeDetailsAccountIdentificationsInner } from './transactionPayeeDetailsAccountIdentificationsInner';


/**
 * Details of the beneficiary [person or business].
 */
export interface TransactionPayeeDetails { 
    /**
     * The account holder name of the Payee.
     */
    name?: string;
    /**
     * The account identifications that identify the Payee\'s bank account.
     */
    accountIdentifications?: Array<TransactionPayeeDetailsAccountIdentificationsInner>;
}

