/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnrichedTransaction } from './enrichedTransaction';
import { TransactionSchedule } from './transactionSchedule';


/**
 * Lists all possible transaction streams identified for the `Application User`.
 */
export interface TransactionStream { 
    /**
     * The name of the Transaction Stream.
     */
    name?: string;
    /**
     * A list of transaction details, identified by Yapily data services.
     */
    transactions?: Array<EnrichedTransaction>;
    transactionSchedule?: TransactionSchedule;
    /**
     * The consistency of the transaction.  This is a number between 0 and 1 with 1 being the most consistent schedule.
     */
    scheduleConsistencyScore?: number;
    /**
     * When is the transaction expected to occur next.
     */
    nextExpectedTransactionDate?: string;
    /**
     * When is the first recorded transaction date
     */
    earliestTransactionDate?: string;
    /**
     * When is the most recent transaction date
     */
    mostRecentTransactionDate?: string;
    /**
     * The consistency of the amount of the transaction.  This is a number between 0 and 1 with 1 being the most consistent amount.
     */
    amountConsistencyScore?: number;
    /**
     * The average amount of the transaction stream
     */
    averageAmount?: number;
}

