/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type TransactionStatusEnum = 'BOOKED' | 'PENDING';

export const TransactionStatusEnum = {
    Booked: 'BOOKED' as TransactionStatusEnum,
    Pending: 'PENDING' as TransactionStatusEnum
};

