/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * The customer segment of the account.
 */
export type UsageType = 'PERSONAL' | 'BUSINESS' | 'OTHER' | 'UNKNOWN';

export const UsageType = {
    Personal: 'PERSONAL' as UsageType,
    Business: 'BUSINESS' as UsageType,
    Other: 'OTHER' as UsageType,
    Unknown: 'UNKNOWN' as UsageType
};

