/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DeleteStatusEnum } from './deleteStatusEnum';
import { ConsentDeleteResponse } from './consentDeleteResponse';


/**
 * Deletion of the user. Includes the user profile and all associate consents.
 */
export interface UserDeleteResponse { 
    /**
     * Unique identifier of the user.
     */
    id?: string;
    deleteStatus?: DeleteStatusEnum;
    /**
     * Date and time that the user was created.
     */
    creationDate?: string;
    userConsents?: Set<ConsentDeleteResponse>;
}
export namespace UserDeleteResponse {
}


