/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Specifies the language and location preferences of the user.
 */
export interface UserSettings { 
    /**
     * 2 letter ISO Language code which denotes the language preference for the `User`.
     */
    language?: string;
    /**
     * 2 letter ISO Country code which denotes the location preference for the `User`.
     */
    location?: string;
}

