/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EnumError } from './enumError';


export interface ValidationError { 
    /**
     * name of the field with error
     */
    fieldName: string;
    error: EnumError;
}
export namespace ValidationError {
}


