/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AlignmentEnum } from './alignmentEnum';
import { FrequencyEnum } from './frequencyEnum';
import { Amount } from './amount';


export interface VrpPeriodicLimit { 
    /**
     * __Mandatory__. Maximum amount that can be specified in all payment instructions in a given period under this VRP consent. If the Alignment is Calendar, the limit is pro-rated in the first period to the remaining number of days.
     */
    maximumAmount: Amount;
    frequency: FrequencyEnum;
    alignment: AlignmentEnum;
}
export namespace VrpPeriodicLimit {
}


