/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HostedVRPLimits } from './hostedVRPLimits';
import { HostedVrpPayerResponse } from './hostedVrpPayerResponse';
import { Amount } from './amount';
import { Payee } from './payee';
import { PaymentRisk } from './paymentRisk';


export interface VRPSetup { 
    payer?: HostedVrpPayerResponse;
    payee: Payee;
    /**
     * __Optional__. The payment reference or description. Limited to a maximum of 18 characters long.
     */
    reference?: string;
    limits?: HostedVRPLimits;
    /**
     * __Optional__. Start date when the consent becomes valid.
     */
    validFrom?: string;
    /**
     * __Optional__. End date when the consent expires and becomes invalid.
     */
    validTo?: string;
    /**
     * The use-case for the VRP consent supported by the bank. Allowed values: <br>`ONGOING` <br>`SUBSCRIPTION`
     */
    recurringPaymentCategory?: string;
    /**
     * __Optional__. Initial payment to be charged under this consent. If enforced, this amount must match the first payment amount executed using this consent.
     */
    initialPayment?: Amount;
    risk?: PaymentRisk;
}

