/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type WebhookStatusType = 'active' | 'paused';

export const WebhookStatusType = {
    Active: 'active' as WebhookStatusType,
    Paused: 'paused' as WebhookStatusType
};

