/**
 * Yapily API
 *
 * Contact: support@yapily.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RegisterWebhook201ResponseData } from './registerWebhook201ResponseData';
import { Metadata } from './metadata';


export interface WebhookDetailsWithSecret { 
    metadata?: Metadata;
    data?: RegisterWebhook201ResponseData;
}

